export const analysisEvents = [
  {
    id: "sprint",
    name: "Sprint",
    label: "100m / 200m",
    score: "8.7/10",
    summary: "11 metrics measured",
    metrics: [
      ["Stride Length", "96%"],
      ["Ground Contact", "0.09s"],
      ["Cadence", "182"],
      ["Acceleration", "Elite"],
      ["Top Speed", "34 km/h"],
      ["Body Lean", "8.8"],
      ["Hip Extension", "91%"],
      ["Arm Drive", "Balanced"],
      ["Knee Lift", "Excellent"],
      ["Symmetry", "97%"],
      ["Form Score", "8.7/10"],
    ],
  },
  {
    id: "hurdles",
    name: "Hurdles",
    label: "100m / 110m",
    score: "8.4/10",
    summary: "13 metrics measured",
    metrics: [
      ["Lead Leg Angle", "Sharp"],
      ["Trail Leg Recovery", "0.31s"],
      ["Clearance Height", "Optimal"],
      ["Take-off Distance", "2.05m"],
      ["Landing Balance", "Stable"],
      ["Rhythm", "Consistent"],
      ["Arm Control", "Good"],
      ["Hip Position", "88%"],
      ["Split Timing", "Strong"],
      ["Stride Between", "3-step"],
      ["Form Score", "8.4/10"],
    ],
  },
  {
    id: "longjump",
    name: "Long Jump",
    label: "Jump Event",
    score: "8.2/10",
    summary: "9 metrics measured",
    metrics: [
      ["Run-up Speed", "Fast"],
      ["Take-off Angle", "21°"],
      ["Board Contact", "Clean"],
      ["Flight Shape", "Good"],
      ["Landing Efficiency", "82%"],
      ["Hip Drive", "Strong"],
      ["Knee Position", "Good"],
      ["Balance", "Stable"],
      ["Form Score", "8.2/10"],
    ],
  },
  {
    id: "highjump",
    name: "High Jump",
    label: "Jump Event",
    score: "8.5/10",
    summary: "10 metrics measured",
    metrics: [
      ["Curve Run", "Controlled"],
      ["Take-off Foot", "Stable"],
      ["Vertical Lift", "Strong"],
      ["Hip Clearance", "91%"],
      ["Bar Clearance", "Clean"],
      ["Shoulder Rotation", "Good"],
      ["Landing Safety", "Safe"],
      ["Approach Speed", "Balanced"],
      ["Body Arch", "Excellent"],
      ["Form Score", "8.5/10"],
    ],
  },
] as const;