export const eventData = [
  {
    id: "sprint",
    name: "Sprint",
    label: "100m / 200m",
    camera: "Side view",
    distance: "35–40 metres",
    fps: "60 FPS",
    duration: "8–12 sec",
    lighting: "Natural daylight",
    quality: 98,
    metrics: [
      "Stride Length",
      "Cadence",
      "Ground Contact",
      "Acceleration",
      "Arm Drive",
      "Top Speed",
    ],
    good: ["Full body visible", "Camera stable", "Track line visible"],
    poor: ["Athlete cropped", "Camera shaking", "Low light"],
  },
  {
    id: "hurdles",
    name: "Hurdles",
    label: "100m / 110m",
    camera: "Side diagonal",
    distance: "25–35 metres",
    fps: "60 FPS",
    duration: "10–15 sec",
    lighting: "Even daylight",
    quality: 94,
    metrics: [
      "Lead Leg",
      "Trail Leg",
      "Clearance",
      "Rhythm",
      "Landing Balance",
      "Split Timing",
    ],
    good: ["Hurdle fully visible", "Approach visible", "Landing visible"],
    poor: ["Only upper body visible", "Hurdle blocked", "Backlit video"],
  },
  {
    id: "longjump",
    name: "Long Jump",
    label: "Jump event",
    camera: "Side view",
    distance: "Runway + pit visible",
    fps: "60 FPS",
    duration: "8–14 sec",
    lighting: "Outdoor daylight",
    quality: 92,
    metrics: [
      "Run-up Speed",
      "Take-off Angle",
      "Board Contact",
      "Flight Shape",
      "Landing Efficiency",
      "Hip Drive",
    ],
    good: ["Board visible", "Full runway visible", "Landing pit visible"],
    poor: ["Board missing", "Landing cropped", "Video too close"],
  },
  {
    id: "highjump",
    name: "High Jump",
    label: "Jump event",
    camera: "45° diagonal",
    distance: "Bar + approach visible",
    fps: "60 FPS",
    duration: "8–14 sec",
    lighting: "Clear daylight",
    quality: 90,
    metrics: [
      "Approach Curve",
      "Take-off Foot",
      "Vertical Lift",
      "Hip Clearance",
      "Bar Clearance",
      "Landing Safety",
    ],
    good: ["Bar visible", "Approach visible", "Landing mat visible"],
    poor: ["Bar cropped", "Camera too low", "Athlete out of frame"],
  },
] as const;

export const comingSoonEvents = [
  "Pole Vault",
  "Triple Jump",
  "Javelin",
  "Discus",
  "Shot Put",
  "Hammer Throw",
  "800m",
  "1500m",
];