// The Digital Athlete Twin's deterministic computation layer. Every
// function here is pure (performances[] in, a plain data shape out) and
// traceable - nothing here calls an LLM, nothing invents a number that
// isn't a direct arithmetic function of stored analysis_result data.
// See docs/ENGINEERING_HANDOFF.md for the architecture proposal this
// implements (audit, parity strategy, metric rules, empty states,
// confidence formula).
import type { MetricDefinition } from "./metricRegistry";
import { METRIC_REGISTRY, getEventName, supportsObjectiveComparison } from "./metricRegistry";

// ---------------------------------------------------------------------
// Trend analysis - ported from backend/app/services/digital_twin_v2/
// statistics.py + trends.py (analyze_longitudinal_trends), with two
// documented, intentional deviations from the Python defaults:
//
// 1. Minimum sample count is 2, not 3 - this platform's own spec
//    ("Digital Twin Progress Engine") requires "Not enough data yet"
//    only below two valid analyses. A 2-point trend still reports a
//    direction (from percent-change/slope), it just never gets
//    reclassified to high_variability (see 2).
// 2. The coefficient-of-variation-based high_variability override
//    (Python: CV% > 15.0) only applies at 3+ samples here - a CV
//    computed from exactly two points isn't a meaningful noise signal,
//    so a 2-point trend can be improving/regressing/stable but never
//    high_variability.
//
// Parity with the Python reference is proven, not asserted - see
// twinEngine.parity.test.ts, which runs this function against the same
// inputs captured from the real Python functions
// (frontend/src/features/performances/lib/__fixtures__/
// twinParity.fixtures.json, generated by backend/scripts/
// generate_twin_parity_fixtures.py) and checks numeric outputs within a
// documented tolerance.
// ---------------------------------------------------------------------

export type TrendDirection =
  | "improving"
  | "regressing"
  | "stable"
  | "high_variability"
  | "insufficient_data";

export interface TrendResult {
  samples: number;
  firstValue: number | null;
  latestValue: number | null;
  absoluteChange: number | null;
  // Not present in the Python reference (analyze_longitudinal_trends
  // only returns absolute_change) - new, simple, unrounded derived
  // value, not subject to parity testing since there's no Python output
  // to check it against.
  percentChange: number | null;
  slopePerSession: number | null;
  coefficientOfVariationPercent: number | null;
  direction: TrendDirection;
}

// Generated from the registry's own comparisonMode field, not hand-
// authored - no metric's "lower is better" direction is hardcoded here or
// anywhere else in this module. This Set exists purely as a compatibility
// layer: classifyDirection/analyzeTrend below are parity-tested against a
// Python reference (twinEngine.parity.test.ts) and must keep their exact
// existing signature (metricKey: string, not a full MetricDefinition), so
// they cannot read `metric.comparisonMode` directly without risking that
// parity contract. Deriving this Set at module load instead gets the same
// metadata-driven result with zero signature risk (docs/
// ENGINEERING_HANDOFF.md §33).
const LOWER_IS_BETTER = new Set<string>(
  METRIC_REGISTRY.filter((m) => m.comparisonMode === "LOWER_IS_BETTER").map((m) => m.key),
);

// Ordinary least squares slope against the equally-spaced session index
// [0..n-1] - NOT calendar time. Matches the Python reference exactly
// (digital_twin_v2/statistics.py::slope), including treating sessions
// as evenly spaced regardless of actual gap length between them.
function computeSlope(values: number[]): number | null {
  const n = values.length;
  if (n < 2) return null;

  const xMean = (n - 1) / 2;
  const yMean = values.reduce((a, b) => a + b, 0) / n;

  let numerator = 0;
  let denominator = 0;
  values.forEach((value, index) => {
    numerator += (index - xMean) * (value - yMean);
    denominator += (index - xMean) ** 2;
  });

  if (denominator <= 1e-12) return 0;
  return numerator / denominator;
}

// Population standard deviation / |mean| * 100 - matches the Python
// reference exactly (uses population, not sample, standard deviation).
function coefficientOfVariationPercent(values: number[]): number | null {
  if (values.length < 2) return null;

  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  if (Math.abs(mean) <= 1e-12) return null;

  const variance =
    values.reduce((acc, value) => acc + (value - mean) ** 2, 0) / values.length;
  const populationStdDev = Math.sqrt(variance);

  return (populationStdDev / Math.abs(mean)) * 100;
}

function classifyDirection(
  metricKey: string,
  slopeValue: number | null,
  practicalThreshold: number,
): TrendDirection {
  if (slopeValue === null) return "insufficient_data";
  if (Math.abs(slopeValue) <= practicalThreshold) return "stable";

  const lowerIsBetter = LOWER_IS_BETTER.has(metricKey);
  const improving = lowerIsBetter ? slopeValue < 0 : slopeValue > 0;
  return improving ? "improving" : "regressing";
}

export function analyzeTrend(metricKey: string, values: number[]): TrendResult {
  const samples = values.length;

  if (samples === 0) {
    return {
      samples: 0,
      firstValue: null,
      latestValue: null,
      absoluteChange: null,
      percentChange: null,
      slopePerSession: null,
      coefficientOfVariationPercent: null,
      direction: "insufficient_data",
    };
  }

  const firstValue = values[0];
  const latestValue = values[samples - 1];

  if (samples < 2) {
    return {
      samples,
      firstValue,
      latestValue,
      absoluteChange: 0,
      percentChange: null,
      slopePerSession: null,
      coefficientOfVariationPercent: null,
      direction: "insufficient_data",
    };
  }

  const slopeValue = computeSlope(values);
  const average = values.reduce((a, b) => a + b, 0) / samples;
  const practicalThreshold = Math.max(Math.abs(average) * 0.0025, 1e-9);

  let direction = classifyDirection(metricKey, slopeValue, practicalThreshold);

  const cv = coefficientOfVariationPercent(values);
  if (samples >= 3 && cv !== null && cv > 15.0) {
    direction = "high_variability";
  }

  const absoluteChange = latestValue - firstValue;
  const percentChange =
    Math.abs(firstValue) > 1e-9 ? (absoluteChange / Math.abs(firstValue)) * 100 : null;

  return {
    samples,
    firstValue,
    latestValue,
    absoluteChange,
    percentChange,
    slopePerSession: slopeValue,
    coefficientOfVariationPercent: cv,
    direction,
  };
}

export interface TrendDisplay {
  label: string;
  tone: "positive" | "negative" | "neutral" | "warning";
}

// Translates a metric's raw statistical trend direction into UI-safe
// language, driven entirely by the metric's own comparisonMode - the
// single place this decision is made. Previously, every consumer
// (TwinTrendChart's DIRECTION_LABEL map) applied "Improving"/"Regressing"
// unconditionally, which meant a rising joint-angle trend was labeled
// "Improving" even though a joint angle has no better/worse direction
// (docs/ENGINEERING_HANDOFF.md §33). Does NOT change analyzeTrend's
// underlying math/output - purely an interpretation layer on top of it.
export function interpretTrendForDisplay(metric: MetricDefinition, trend: TrendResult): TrendDisplay {
  if (trend.direction === "insufficient_data") {
    return { label: "Not enough data yet", tone: "neutral" };
  }
  if (trend.direction === "high_variability") {
    return { label: "High variability", tone: "warning" };
  }
  if (trend.direction === "stable") {
    return { label: "Stable", tone: "neutral" };
  }

  // trend.direction is "improving" or "regressing" here - analyzeTrend
  // already accounts for LOWER_IS_BETTER when computing this (see
  // classifyDirection), so "improving" already means "the right
  // direction for this metric" whenever an objective direction exists.
  if (supportsObjectiveComparison(metric.comparisonMode)) {
    return trend.direction === "improving"
      ? { label: "Improving", tone: "positive" }
      : { label: "Regressing", tone: "negative" };
  }

  // NEUTRAL / EXPERIMENTAL / NOT_COMPARABLE / TARGET_RANGE - the raw
  // value changed, but no direction is objectively "better" - report the
  // fact, never a value judgment.
  return trend.direction === "improving"
    ? { label: "Increased", tone: "neutral" }
    : { label: "Decreased", tone: "neutral" };
}

// A metric may only ever generate a strength, a development area, an
// evolution statement, or a personal best if it's production-status, not
// hidden, eligible for the Twin, and its comparisonMode supports an
// objective "better" direction at all (docs/ENGINEERING_HANDOFF.md §33) -
// a NEUTRAL joint angle must never produce "Improving Left Knee Angle"
// text (or a "Personal Best" card) just because its trend slope happens
// to be positive.
function isTwinNarrativeEligible(metric: MetricDefinition): boolean {
  return (
    metric.status === "production" &&
    !metric.hidden &&
    metric.supportsTwin &&
    supportsObjectiveComparison(metric.comparisonMode)
  );
}

// ---------------------------------------------------------------------
// Personal bests - ported from backend/app/services/digital_twin/
// personal_bests.py::find_personal_best. On ties, the earliest-recorded
// point wins (Python's min/max only replace the running best on a
// strictly smaller/larger value, so ties keep the first occurrence -
// replicated here with strict </> comparisons in the same left-to-right
// reduce order).
// ---------------------------------------------------------------------

export interface PersonalBestPoint {
  performanceId: string;
  recordedAt: string;
  value: number;
}

export interface PersonalBestResult {
  metricKey: string;
  value: number;
  performanceId: string;
  recordedAt: string;
  objective: "minimum" | "maximum";
}

export function findPersonalBest(
  metricKey: string,
  points: PersonalBestPoint[],
  lowerIsBetter: boolean,
): PersonalBestResult | null {
  if (points.length === 0) return null;

  let best = points[0];
  for (let i = 1; i < points.length; i++) {
    const candidate = points[i];
    if (lowerIsBetter ? candidate.value < best.value : candidate.value > best.value) {
      best = candidate;
    }
  }

  return {
    metricKey,
    value: best.value,
    performanceId: best.performanceId,
    recordedAt: best.recordedAt,
    objective: lowerIsBetter ? "minimum" : "maximum",
  };
}

// ---------------------------------------------------------------------
// Session extraction helpers - shared plumbing every section below
// builds on. A "session" here means one completed performance with a
// real analysis_result; grouping/filtering rules matching the amended
// architecture proposal (§08 metric rules, §11 version compatibility).
// ---------------------------------------------------------------------

export interface TwinSessionInput {
  id: string;
  performanceNumber: number;
  performanceDate: string | null;
  createdAt: string;
  events: unknown;
  uploadStatus: string | null;
  analysisResult: any;
}

// Shared row->TwinSessionInput mapping - both the athlete's own Twin
// page and any other console viewing a set of `performances` rows
// (e.g. the Coach Console's single-athlete progress page) need the
// exact same shape, whether the rows came from usePerformances (athlete
// owner) or getConnectedAthletePerformances (coach/academy, same
// columns per connections.service.ts). One mapping, not a copy per
// consumer.
export function toTwinSessionInput(p: any): TwinSessionInput {
  return {
    id: p.id,
    performanceNumber: p.performance_number ?? 0,
    performanceDate: p.performance_date ?? null,
    createdAt: p.created_at,
    events: p.events,
    uploadStatus: p.upload_status,
    analysisResult: p.analysis_result,
  };
}

function completedSessions(performances: TwinSessionInput[]): TwinSessionInput[] {
  return performances.filter((p) => p.uploadStatus === "completed" && p.analysisResult);
}

function sessionDate(session: TwinSessionInput): string {
  return session.performanceDate ?? session.createdAt;
}

// §11: group by provider (the only real version-ish signal that exists
// today) and use only the dominant group for any multi-session
// computation - never silently blend sessions from different pipelines.
export interface ProviderGrouping {
  dominant: TwinSessionInput[];
  dominantProvider: string | null;
  excludedCount: number;
}

export function groupByDominantProvider(sessions: TwinSessionInput[]): ProviderGrouping {
  if (sessions.length === 0) {
    return { dominant: [], dominantProvider: null, excludedCount: 0 };
  }

  const groups = new Map<string, TwinSessionInput[]>();
  for (const session of sessions) {
    const provider = String(session.analysisResult?.provider ?? "unknown");
    const group = groups.get(provider) ?? [];
    group.push(session);
    groups.set(provider, group);
  }

  // Tie-break (§28 verification - a real, reproducible bug found and
  // fixed here): with an EXACT count tie between two provider groups
  // (e.g. one rtmpose session, one mediapipe session), comparing only
  // `group.length > dominant.length` let whichever provider happened to
  // be iterated first - i.e. whichever session came first in the input
  // array - silently win, which meant shuffling/reordering the same
  // sessions could flip which provider was treated as "dominant."
  // Breaking ties by each group's own latest session date instead is
  // order-independent (it depends on the sessions' own timestamps, not
  // their position in the input array) and a defensible product rule in
  // its own right: when two pipelines are equally represented, trust the
  // one used most recently.
  let dominantProvider = "";
  let dominant: TwinSessionInput[] = [];
  let dominantLatestTime = -Infinity;
  for (const [provider, group] of groups) {
    const latestTime = Math.max(...group.map((s) => new Date(sessionDate(s)).getTime()));
    if (
      group.length > dominant.length ||
      (group.length === dominant.length && latestTime > dominantLatestTime)
    ) {
      dominant = group;
      dominantProvider = provider;
      dominantLatestTime = latestTime;
    }
  }

  return {
    dominant: [...dominant].sort(
      (a, b) => new Date(sessionDate(a)).getTime() - new Date(sessionDate(b)).getTime(),
    ),
    dominantProvider,
    excludedCount: sessions.length - dominant.length,
  };
}

interface MetricSeriesPoint {
  performanceId: string;
  recordedAt: string;
  value: number;
  coveragePercent?: number;
}

function extractMetricSeries(
  sessions: TwinSessionInput[],
  metric: MetricDefinition,
): MetricSeriesPoint[] {
  return sessions
    .map((session): MetricSeriesPoint | null => {
      const extracted = metric.accessor(session.analysisResult);
      if (!extracted) return null;
      // Same unreliability gate PartnerCompare's checkMetricComparability
      // already applies for pairwise comparison - a value below
      // minCoveragePercent is unreliable regardless of whether it's
      // being compared to another athlete or trended over time for this
      // one, so it's excluded here too (treated as "not present," not
      // as a bad-but-counted sample) rather than silently feeding a
      // trend, a strength, or a personal best.
      if (
        metric.minCoveragePercent !== undefined &&
        extracted.coveragePercent !== undefined &&
        extracted.coveragePercent < metric.minCoveragePercent
      ) {
        return null;
      }
      return {
        performanceId: session.id,
        recordedAt: sessionDate(session),
        value: extracted.value,
        coveragePercent: extracted.coveragePercent,
      };
    })
    .filter((point): point is MetricSeriesPoint => point !== null);
}

// ---------------------------------------------------------------------
// Twin metric trend - the public entry point combining provider
// grouping + per-metric extraction + analyzeTrend, for one metric.
// ---------------------------------------------------------------------

export interface TwinMetricTrend {
  metric: MetricDefinition;
  trend: TrendResult;
  points: { performanceId: string; recordedAt: string; value: number }[];
  excludedByProvider: number;
}

export function buildTwinMetricTrend(
  performances: TwinSessionInput[],
  metric: MetricDefinition,
): TwinMetricTrend {
  const { dominant, excludedCount } = groupByDominantProvider(completedSessions(performances));
  const points = extractMetricSeries(dominant, metric);
  const values = points.map((p) => p.value);

  return {
    metric,
    trend: analyzeTrend(metric.key, values),
    points,
    excludedByProvider: excludedCount,
  };
}

// ---------------------------------------------------------------------
// Traceability (§28 verification pass) - debug/test-only helper, not
// wired into any athlete- or coach-facing component. Answers "why does
// this number say what it says" for a single metric by re-running the
// exact same inclusion logic buildTwinMetricTrend uses internally, but
// returning a per-session reason instead of a final number. Exported so
// it's reachable from tests and a future dev-only debug panel, never
// meant to appear in the athlete UI - "included: false" reasons name
// real thresholds (upload status, provider mismatch, missing value,
// coverage), not implementation details a non-engineer couldn't verify
// against the same row in Supabase.
export interface SessionInclusionTrace {
  performanceId: string;
  performanceNumber: number;
  recordedAt: string;
  uploadStatus: string | null;
  included: boolean;
  reason: string;
}

export function traceMetricInclusion(
  performances: TwinSessionInput[],
  metric: MetricDefinition,
): SessionInclusionTrace[] {
  const { dominant, dominantProvider } = groupByDominantProvider(completedSessions(performances));
  const dominantIds = new Set(dominant.map((s) => s.id));

  return performances.map((session): SessionInclusionTrace => {
    const recordedAt = sessionDate(session);
    const base = {
      performanceId: session.id,
      performanceNumber: session.performanceNumber,
      recordedAt,
      uploadStatus: session.uploadStatus,
    };

    if (session.uploadStatus !== "completed" || !session.analysisResult) {
      return {
        ...base,
        included: false,
        reason: `upload_status is "${session.uploadStatus ?? "unknown"}" (or no analysis_result exists) - only completed, analysed sessions are eligible.`,
      };
    }

    if (!dominantIds.has(session.id)) {
      const provider = String(session.analysisResult?.provider ?? "unknown");
      return {
        ...base,
        included: false,
        reason: `Generated by a different pipeline ("${provider}") than this athlete's dominant "${dominantProvider}" group - excluded rather than blended with incompatible analyses.`,
      };
    }

    const extracted = metric.accessor(session.analysisResult);
    if (!extracted) {
      return {
        ...base,
        included: false,
        reason: `"${metric.label}" has no value in this session (not computed, or biomechanics was skipped for this session).`,
      };
    }

    if (
      metric.minCoveragePercent !== undefined &&
      extracted.coveragePercent !== undefined &&
      extracted.coveragePercent < metric.minCoveragePercent
    ) {
      return {
        ...base,
        included: false,
        reason: `Coverage (${extracted.coveragePercent}%) is below the ${metric.minCoveragePercent}% trust threshold for "${metric.label}".`,
      };
    }

    return {
      ...base,
      included: true,
      reason: `Included in the "${dominantProvider}" dominant-provider group with a valid "${metric.label}" value (${extracted.value}).`,
    };
  });
}

// ---------------------------------------------------------------------
// Personal bests across the registry - isTwinNarrativeEligible() gates
// this the same way as strengths/development areas (docs/
// ENGINEERING_HANDOFF.md §33): experimental metrics (ground contact / duty
// factor / flight time) stay display-only, AND - fixed this pass - a
// NEUTRAL metric (joint angles) can no longer produce a "Personal Best"
// card either, since there's no objective better/worse direction to pick
// one. Previously this filtered on production-status alone, which meant
// the Twin could render "Personal Best: Left Knee Angle."
// ---------------------------------------------------------------------

export function buildTwinPersonalBests(
  performances: TwinSessionInput[],
): (PersonalBestResult & { label: string; unit: string })[] {
  const { dominant } = groupByDominantProvider(completedSessions(performances));

  return METRIC_REGISTRY.filter(isTwinNarrativeEligible)
    .map((metric) => {
      const points = extractMetricSeries(dominant, metric);
      if (points.length === 0) return null;

      const best = findPersonalBest(
        metric.key,
        points,
        metric.comparisonMode === "LOWER_IS_BETTER",
      );
      if (!best) return null;

      return { ...best, label: metric.label, unit: metric.unit };
    })
    .filter(
      (pb): pb is PersonalBestResult & { label: string; unit: string } => pb !== null,
    );
}

// ---------------------------------------------------------------------
// Consistency - Step 7. Every sub-metric here is a plain ratio/CV over
// data already computed elsewhere on the page - nothing new invented.
// ---------------------------------------------------------------------

export interface ConsistencySummary {
  uploadFrequencyDays: number | null; // median days between uploads
  sessionCompletionRatePercent: number | null; // completed / (completed+failed), uploaded-only excluded (still in flight)
  recordingConsistencyCvPercent: number | null; // CV of readiness score across sessions
  metricStabilityCvPercent: number | null; // average CV across production biomechanics metrics
  sampleSize: number;
}

export function computeConsistency(performances: TwinSessionInput[]): ConsistencySummary {
  const completed = completedSessions(performances);
  const { dominant } = groupByDominantProvider(completed);

  const terminal = performances.filter(
    (p) => p.uploadStatus === "completed" || p.uploadStatus === "failed",
  );
  const sessionCompletionRatePercent =
    terminal.length > 0 ? (completed.length / terminal.length) * 100 : null;

  const sortedDates = dominant
    .map((s) => new Date(sessionDate(s)).getTime())
    .sort((a, b) => a - b);
  let uploadFrequencyDays: number | null = null;
  if (sortedDates.length >= 2) {
    const gaps = sortedDates.slice(1).map((t, i) => (t - sortedDates[i]) / (1000 * 60 * 60 * 24));
    const sortedGaps = [...gaps].sort((a, b) => a - b);
    const mid = Math.floor(sortedGaps.length / 2);
    uploadFrequencyDays =
      sortedGaps.length % 2 === 0
        ? (sortedGaps[mid - 1] + sortedGaps[mid]) / 2
        : sortedGaps[mid];
  }

  const readinessMetric = METRIC_REGISTRY.find((m) => m.key === "readiness_score")!;
  const readinessValues = extractMetricSeries(dominant, readinessMetric).map((p) => p.value);
  const recordingConsistencyCvPercent = coefficientOfVariationPercent(readinessValues);

  const stabilityCvs = METRIC_REGISTRY.filter(
    (m) => m.status === "production" && m.category === "biomechanics",
  )
    .map((metric) => {
      const values = extractMetricSeries(dominant, metric).map((p) => p.value);
      return coefficientOfVariationPercent(values);
    })
    .filter((cv): cv is number => cv !== null);

  const metricStabilityCvPercent =
    stabilityCvs.length > 0
      ? stabilityCvs.reduce((a, b) => a + b, 0) / stabilityCvs.length
      : null;

  return {
    uploadFrequencyDays,
    sessionCompletionRatePercent,
    recordingConsistencyCvPercent,
    metricStabilityCvPercent,
    sampleSize: dominant.length,
  };
}

// ---------------------------------------------------------------------
// Twin confidence - Step 10. A documented, transparent formula (NOT the
// Python readiness.py's injury-risk heuristic, and NOT engine.py's
// geometric mean of measurement confidences - neither is "twin
// confidence" as specified). Every factor is a plain average/ratio over
// data already rendered elsewhere on the page. See the architecture
// proposal §12 for the worked formula this implements verbatim.
// ---------------------------------------------------------------------

export type ConfidenceLevel = "high" | "medium" | "low";

export interface TwinConfidence {
  score: number; // 0-100
  level: ConfidenceLevel;
  factors: {
    sessionCountScore: number;
    recordingQualityScore: number;
    completenessScore: number;
    algorithmConfidenceScore: number;
  };
  sessionCount: number;
}

export function computeTwinConfidence(performances: TwinSessionInput[]): TwinConfidence | null {
  // Gated by dominant provider like every other multi-session
  // computation (§11) - a session from an incompatible pipeline
  // shouldn't inflate sessionCount or pull the readiness/detection
  // averages toward a value the rest of the Twin excludes.
  const { dominant: completed } = groupByDominantProvider(completedSessions(performances));
  if (completed.length === 0) return null;

  const readinessMetric = METRIC_REGISTRY.find((m) => m.key === "readiness_score")!;
  const detectionMetric = METRIC_REGISTRY.find((m) => m.key === "detection_rate")!;

  const readinessValues = extractMetricSeries(completed, readinessMetric).map((p) => p.value);
  const detectionValues = extractMetricSeries(completed, detectionMetric).map((p) => p.value);

  const avgReadiness =
    readinessValues.length > 0
      ? readinessValues.reduce((a, b) => a + b, 0) / readinessValues.length
      : 0;
  const avgDetection =
    detectionValues.length > 0
      ? detectionValues.reduce((a, b) => a + b, 0) / detectionValues.length
      : 0;

  const sessionsWithBiomechanics = completed.filter(
    (s) => s.analysisResult?.biomechanics?.status !== "skipped",
  ).length;

  const sessionCountScore = Math.min(completed.length / 5, 1) * 40;
  const recordingQualityScore = (avgReadiness / 100) * 25;
  const completenessScore = (sessionsWithBiomechanics / completed.length) * 20;
  const algorithmConfidenceScore = (avgDetection / 100) * 15;

  const score =
    sessionCountScore + recordingQualityScore + completenessScore + algorithmConfidenceScore;

  const level: ConfidenceLevel = score >= 75 ? "high" : score >= 45 ? "medium" : "low";

  return {
    score,
    level,
    factors: {
      sessionCountScore,
      recordingQualityScore,
      completenessScore,
      algorithmConfidenceScore,
    },
    sessionCount: completed.length,
  };
}

// ---------------------------------------------------------------------
// Strengths / Development Areas - Steps 5-6. Rule-based, deterministic,
// derived only from analyzeTrend()/consistency output - never an LLM.
// Only isTwinNarrativeEligible() metrics qualify (docs/ENGINEERING_HANDOFF.md
// §33): production-status, not hidden, Twin-eligible, AND comparisonMode
// must support an objective direction. Ground contact/duty factor/flight
// time are excluded because they're experimental; joint angles are
// excluded because a bigger/smaller angle isn't "better" - neither can
// ever generate a strength or a development area.
// ---------------------------------------------------------------------

export interface TwinObservation {
  key: string;
  label: string;
  category: "recording_quality" | "biomechanics";
  detail: string;
}

export function deriveStrengths(
  performances: TwinSessionInput[],
): TwinObservation[] {
  const observations: TwinObservation[] = [];

  for (const metric of METRIC_REGISTRY) {
    if (!isTwinNarrativeEligible(metric)) continue;

    const { trend } = buildTwinMetricTrend(performances, metric);
    if (trend.samples < 2) continue;

    const isConsistent =
      trend.coefficientOfVariationPercent !== null &&
      trend.coefficientOfVariationPercent < 8 &&
      (trend.direction === "stable" || trend.direction === "improving");

    if (isConsistent) {
      observations.push({
        key: `${metric.key}-consistent`,
        label: `Consistent ${metric.label.toLowerCase()}`,
        category: metric.category,
        detail: `${metric.label} has stayed within ${trend.coefficientOfVariationPercent!.toFixed(1)}% variation across ${trend.samples} analysed sessions.`,
      });
    }

    if (trend.direction === "improving" && trend.percentChange !== null && trend.percentChange > 3) {
      observations.push({
        key: `${metric.key}-improving`,
        label: `Improving ${metric.label.toLowerCase()}`,
        category: metric.category,
        detail: `${metric.label} has increased ${Math.abs(trend.percentChange).toFixed(1)}% over the past ${trend.samples} analysed sessions.`,
      });
    }
  }

  return observations;
}

export function deriveDevelopmentAreas(
  performances: TwinSessionInput[],
): TwinObservation[] {
  const observations: TwinObservation[] = [];
  // Gated by dominant provider (§11) - a minority-pipeline session
  // shouldn't count toward or against the biomechanics-availability
  // ratio below, same reasoning as every other multi-session stat here.
  const { dominant: completed } = groupByDominantProvider(completedSessions(performances));

  for (const metric of METRIC_REGISTRY) {
    if (!isTwinNarrativeEligible(metric)) continue;

    const { trend } = buildTwinMetricTrend(performances, metric);
    if (trend.samples < 2) continue;

    if (trend.direction === "high_variability") {
      observations.push({
        key: `${metric.key}-inconsistent`,
        label: `${metric.label} inconsistent`,
        category: metric.category,
        detail: `${metric.label} has varied by ${trend.coefficientOfVariationPercent!.toFixed(1)}% across ${trend.samples} analysed sessions - more than would be expected session to session.`,
      });
    }

    if (trend.direction === "regressing" && trend.percentChange !== null) {
      observations.push({
        key: `${metric.key}-regressing`,
        label: `${metric.label} declining slowly`,
        category: metric.category,
        detail: `${metric.label} has decreased ${Math.abs(trend.percentChange).toFixed(1)}% over the past ${trend.samples} analysed sessions.`,
      });
    }
  }

  // Biomechanics availability, independent of any single metric's own
  // trend - directly answers the spec's own example ("ground-contact
  // metrics unavailable due to recording quality").
  if (completed.length >= 2) {
    const withBiomechanics = completed.filter(
      (s) => s.analysisResult?.biomechanics?.status !== "skipped",
    ).length;
    const ratio = withBiomechanics / completed.length;

    if (ratio < 0.7) {
      observations.push({
        key: "biomechanics-availability",
        label: "Biomechanics unavailable in most sessions",
        category: "recording_quality",
        detail: `Biomechanics analysis was only available for ${withBiomechanics} of ${completed.length} completed sessions - usually caused by camera angle or body visibility, see each report's Limitations section.`,
      });
    }
  }

  return observations;
}

// ---------------------------------------------------------------------
// Evolution statements - Step 9. Template-filled from analyzeTrend()'s
// own numbers, never free-generated text.
// ---------------------------------------------------------------------

export function generateEvolutionStatements(performances: TwinSessionInput[]): string[] {
  const statements: string[] = [];

  for (const metric of METRIC_REGISTRY) {
    if (!isTwinNarrativeEligible(metric)) continue;

    const { trend } = buildTwinMetricTrend(performances, metric);
    if (trend.samples < 2 || trend.percentChange === null) continue;
    if (trend.direction !== "improving" && trend.direction !== "regressing") continue;

    const verb = trend.direction === "improving" ? "increased" : "decreased";
    statements.push(
      `${metric.label} has ${verb} ${Math.abs(trend.percentChange).toFixed(1)}% over the past ${trend.samples} analysed sessions.`,
    );
  }

  // Gated by dominant provider (§11), same reasoning as
  // deriveDevelopmentAreas's identical check.
  const { dominant: completed } = groupByDominantProvider(completedSessions(performances));
  if (completed.length >= 2) {
    const withBiomechanics = completed.filter(
      (s) => s.analysisResult?.biomechanics?.status !== "skipped",
    );
    const sortedByDate = [...completed].sort(
      (a, b) => new Date(sessionDate(a)).getTime() - new Date(sessionDate(b)).getTime(),
    );
    const firstHalf = sortedByDate.slice(0, Math.ceil(sortedByDate.length / 2));
    const secondHalf = sortedByDate.slice(Math.ceil(sortedByDate.length / 2));
    const firstRatio =
      firstHalf.filter((s) => s.analysisResult?.biomechanics?.status !== "skipped").length /
      firstHalf.length;
    const secondRatio =
      secondHalf.filter((s) => s.analysisResult?.biomechanics?.status !== "skipped").length /
      secondHalf.length;

    if (secondRatio - firstRatio > 0.2) {
      statements.push(
        `Biomechanics availability has increased from ${Math.round(firstRatio * 100)}% to ${Math.round(secondRatio * 100)}% of sessions.`,
      );
    }
    void withBiomechanics;
  }

  return statements;
}

// ---------------------------------------------------------------------
// Convenience: the event name a Twin should be built for - the most
// common event among an athlete's completed sessions, so a rare
// off-event upload doesn't fragment every metric into two tiny groups.
// ---------------------------------------------------------------------

export function dominantEventName(performances: TwinSessionInput[]): string | null {
  const completed = completedSessions(performances);
  if (completed.length === 0) return null;

  const counts = new Map<string, number>();
  for (const session of completed) {
    const name = getEventName(session.events);
    counts.set(name, (counts.get(name) ?? 0) + 1);
  }

  let best: string | null = null;
  let bestCount = 0;
  for (const [name, count] of counts) {
    if (count > bestCount) {
      best = name;
      bestCount = count;
    }
  }
  return best;
}

// "Current Development Stage" - Step 2. Deliberately a data-maturity
// label (how much of a Twin exists yet), not an athletic-skill
// assessment - deterministic from completed session count alone, never
// a coaching judgment.
export type DevelopmentStage = "no_twin" | "just_starting" | "building_baseline" | "established";

export function deriveDevelopmentStage(performances: TwinSessionInput[]): {
  stage: DevelopmentStage;
  label: string;
} {
  const count = completedSessions(performances).length;

  if (count === 0) return { stage: "no_twin", label: "No Twin Yet" };
  if (count === 1) return { stage: "just_starting", label: "Just Starting" };
  if (count <= 4) return { stage: "building_baseline", label: "Building a Baseline" };
  return { stage: "established", label: "Established Profile" };
}
